source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in app_component.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

# workaround the fact that original trueskill is from 2011, and below fork is from 2014.
# Has to be bundled from component directory instead of app directory, because bundling from app directory would ignore below lines
gem "trueskill",
  git: "https://github.com/benjaminleesmith/trueskill",
  ref: "e404f45af5b3fb86982881ce064a9c764cc6a901"