# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rspec', '~> 3.6'
gem 'coderay', '~> 1.1', '>= 1.1.2'
gem 'rack-test', '~> 0.8.3'
gem 'sinatra', '~> 2.2'
gem 'sequel', '~> 4.49'
gem 'sqlite3', '~> 1.3', '>= 1.3.13'
